yaml
name: sendtalk
description: Offline mesh chat and voice app
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  cryptography: ^2.5.0
  flutter_blue_plus: ^1.31.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true